config/routes.rb
Rails.application.routes.draw do
    devise_for :users
    root "welcome#index"
  
    resources :groups do
      resources :entities
    end
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  # root "posts#index"
end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)
    user ||= User.new

    if user.admin?
      can :manage, :all
    else
      can :read, Group, user_id: user.id
      # other abilities...
    end
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/entity.rb
# app/models/entity.rb
class Entity < ApplicationRecord
  belongs_to :author, class_name: 'User', foreign_key: 'author_id'
  has_many :entity_groups
  has_many :groups, through: :entity_groups

  validates :name, presence: true
end

app/models/entity_group.rb
# app/models/entity_group.rb
class EntityGroup < ApplicationRecord
  belongs_to :entity
  belongs_to :group
end

app/models/group.rb
# app/models/group.rb
# app/models/group.rb
class Group < ApplicationRecord
  belongs_to :user
  has_many :entity_groups
  has_many :entities, through: :entity_groups

  validates :name, presence: true

  def total
    @total_cost = 0
    entity_groups.includes(:entity).each do |entity_group|
      @total_cost += entity_group.entity.amount
    end
    @total_cost
  end
end

app/models/user.rb
# app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :entities, foreign_key: 'author_id'
  has_many :groups, foreign_key: 'user_id'

  validates :name, presence: true

  def admin?
    role == 'admin'
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def after_sign_in_path_for(_resource)
    groups_path
  end

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name])
  end
end

app/controllers/entities_controller.rb
class EntitiesController < ApplicationController
  before_action :set_entity, only: %i[show edit update destroy]

  def index
    @page = 'TRANSACTIONS'
    @group = Group.find(params[:group_id])
    @group_entities = EntityGroup.where(group_id: params[:group_id]).order('created_at DESC')
    @entities = []
    @group_entities.each do |entity_group|
      entity = Entity.find(entity_group.entity_id)
      @entities << entity
    end
  end

  def show; end

  def new
    @page = 'NEW TRANSACTION'
    @id = params[:group_id]
    @name = Group.find(params[:group_id]).name
    @entity = Entity.new
    @group = Group.find(params[:group_id])
    @entity = @group.entities.build
  end

  def edit; end

  def create
    @entity = Entity.new(entity_params)
    @entity_group = EntityGroup.new(group: Group.find(params[:group_id]), entity: @entity)

    respond_to do |format|
      if @entity.save && @entity_group.save
        format.html do
          redirect_to "/groups/#{params[:group_id]}/entities", notice: 'Transaction was successfully created.'
        end
        format.json { render :show, status: :created, location: @entity }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @entity.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    respond_to do |format|
      if @entity.update(entity_params)
        format.html { redirect_to entity_url(@entity), notice: 'Entity was successfully updated.' }
        format.json { render :show, status: :ok, location: @entity }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @entity.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @entity.destroy

    respond_to do |format|
      format.html { redirect_to entities_url, notice: 'Entity was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private

  def set_entity
    @entity = Entity.find(params[:id])
  end

  def entity_params
    params.require(:entity).permit(:name, :amount).merge(author: current_user)
  end
end

app/controllers/groups_controller.rb
class GroupsController < ApplicationController
  before_action :set_group, only: %i[show update destroy]

  def index
    @page = 'CATEGORIES'
    @groups = Group.all
  end

  def new
    @page = 'NEW CATEGORY'
    @group = Group.new
    original_categories = %w[Studies Housing Transportation Foods Utilities Clothing Healthcare Entertainment Personal
                             Savings]
    @categories = original_categories.shuffle
  end

  def show; end

  def create
    @group = Group.new(group_params)
    @group.icon = "#{@group.name}.jpg"

    respond_to do |format|
      if @group.save
        format.html { redirect_to groups_url, notice: 'Category was successfully created.' }
        format.json { render :show, status: :created, location: @group }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @group.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    respond_to do |format|
      if @group.update(group_params)
        format.html { redirect_to group_url(@group), notice: 'Group was successfully updated.' }
        format.json { render :show, status: :ok, location: @group }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @group.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @group.destroy

    respond_to do |format|
      format.html { redirect_to groups_path, notice: 'Group deleted' }
    end
  end

  private

  def set_group
    @group = Group.find(params[:id])
  end

  def group_params
    params.require(:group).permit(:name).merge(user: current_user)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: %i[show edit update destroy]

  # GET /users or /users.json
  def index
    @users = User.all
  end

  # GET /users/1 or /users/1.json
  def show; end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit; end

  # POST /users or /users.json
  def create
    @user = User.new(user_params)

    respond_to do |format|
      if @user.save
        format.html { redirect_to user_url(@user), notice: 'User was successfully created.' }
        format.json { render :show, status: :created, location: @user }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /users/1 or /users/1.json
  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to user_url(@user), notice: 'User was successfully updated.' }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1 or /users/1.json
  def destroy
    @user.destroy!

    respond_to do |format|
      format.html { redirect_to users_url, notice: 'User was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_user
    @user = User.find(params[:id])
  end

  # Only allow a list of trusted parameters through.
  def user_params
    params.require(:user).permit(:name)
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index; end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/entities_helper.rb
module EntitiesHelper
end

app/helpers/groups_helper.rb
module GroupsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/entities/index.html.erb
<div>
  <h1><%= @group.name %></h1>
  <h3 class="welcome-p">Total Amount: $<%= @group.total %></h3>
  <% if @entities.empty? %>
    <h3>No Activities Here</h3>
    <%= image_tag("low.jpg", id: '1690915255103-img', class: 'empty-img') %>
  <% else %>
    <div>
      <% @entities.each do |entity| %>
        <div class="activity">
          <div>
            <%= image_tag("transactions.webp", id: '1690915255103-img', class: 'empty-img') %>
          </div>
          <div class="activity-container">
            <h2 class="h2"><%= entity.name %></h2>
            <h3 class="welcome-p">$<%= entity.amount %></h3>
          </div>
        </div>
      <% end %>
    </div>
  <% end %>
</div>
<%= link_to "New Transaction", new_group_entity_path(@group), class: 'categories-button' %>

app/views/entities/new.html.erb
<div class="register-container">
  <%= form_with model: @entity, url: group_entities_path(@group) do |form| %>
    <div>
      <%= form.label :name, style: "display: block" %>
      <%= form.text_field :name, required: true, class: "form-control" %>
    </div>

    <div>
      <%= form.label :amount, style: "display: block" %>
      <%= form.number_field :amount, required: true, class: "form-control" %>
    </div>

    <div>
      <%= form.submit "Add transaction", class: "submit-btn" %>
    </div>
  <% end %>
  <%= link_to "Back", group_entities_path(@group), class: 'categories-button' %>
</div>

app/views/groups/index.html.erb
<div class="big-container">
  <% if @groups.empty? || can?(:create, Group) %>
    <h3 class="welcome-p">No categories</h3>
    <%= image_tag("low.jpg", id: '1690915255103-img', class: 'empty-img') %>
  <% else %>
    <div class="groups">
      <% group_image_mapping = {
           'Foods' => 'food.jpg',
           'Studies' => 'studies.jpg',
           'Clothing' => 'clothing.jpg',
           'Healthcare' => 'health.jpg',
           'Transportation' => 'transportation.jpg',
           'Utilities' => 'utilities.jpg',
           'Entertainment' => 'entertainment.jpg',
           'Housing' => 'housing.jpg',
           'Savings' => 'savings.jpg',
           'Personal' => 'personal.png'
        } %>

      <% @groups.each do |group| %>
        <% if can?(:read, group) %>
          <div class="group-container">
            <div>
              <% image_filename = group_image_mapping[group.name] %>
              <%= image_tag(image_filename, id: '1690915255103-img', class: 'group-img') if image_filename %>
            </div>
            <div class="group-flex">
              <div>
                <h1 class="group_name"><%= group.name %></h1>
                <h3 class="welcome-p">Total Amount: $<%= group.total %></h3>
              </div>
              <div class="group-links">
                <a href="<%= "/groups/#{group.id}/entities" %>" class="btn-back-2">
                  <i class="fa-solid fa-eye fa-dif"></i>
                </a>

                  <%= button_to group_path(group),
                                method: :delete,
                                data: { turbolinks_confirm: 'Delete this category?' },
                                class: 'btn-back',
                                form: { class: 'delete-form' } do %>
                    <i class="fa-solid fa-trash-can fa-dif"></i>
                  <% end %>
              </div>
            </div>
          </div>
        <% end %>
      <% end %>
    </div>
  <% end %>
</div>
<%= link_to "New Category", new_group_path, class: 'categories-button' %>

app/views/groups/new.html.erb
<div class="register-container">
  <%= form_with(model: @group) do |form| %>

      <div>
        <%= form.label :name, style: "display: block" %>
        <%= form.select :name, @categories, { :include_blank => '-- Select One --' }, class: "form-control", required: true %>
      </div>

      <div>
        <%= form.submit 'Add-category', class: "submit-btn" %>
      </div>
    <% end %>
  </div>
  <div>

</div>
<%= link_to "Back", groups_path, class: 'categories-button' %>

app/views/groups/show.html.erb
<h2><%= @group.name %></h2>
<a href=<%= groups_path %> id="signup-btn">Back <i class="fa-solid fa-arrow-left"></i></i></a>
<%# gorp-show %>

app/views/layouts/_navbar.html.erb
<header class="header">
  <% if user_signed_in? %>
    <div class="nav">
      <% if @page == 'CATEGORIES' %>
        <i class="fa-solid fa-bars"></i>
      <% else %>
        <a href=<%= groups_path %> class="signup-btn"><i class="fa-solid fa-arrow-left"></i></i></a>
      <% end %>
      <h1 class="group_name"><%= @page %></h1>
      <%= button_to 'Sign out', destroy_user_session_path, method: :delete, class: 'btn btn-so' %>
    </div>
  <% else %>
    <div class="nav-2">
      <h1>REGISTER</h1>
    </div>
  <% end %>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>BudgetApp</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.4.2/css/all.min.css" integrity="sha512-z3gLpd7yknf1YoNbCzqRKc4qyor8gaKU1qmn+CShxbuBusANI9QpRohGBreCFkKxLhei6S9CQXFEbbKuqLg0DA==" crossorigin="anonymous" referrerpolicy="no-referrer" />
  </head>

  <body>
    <%= render 'layouts/navbar' %>
    
    <p class="alert"><%= alert %></p>
    <%= yield %>
  </body>
</html>

app/views/users/_form.html.erb
<%= form_with(model: user) do |form| %>
  <% if user.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
        <% user.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :name, style: "display: block" %>
    <%= form.text_field :name %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/users/_user.html.erb
<div id="<%= dom_id user %>">
  <p>
    <strong>Name:</strong>
    <%= user.name %>
  </p>

</div>

app/views/users/edit.html.erb
<h1>Editing user</h1>

<%= render "form", user: @user %>

<br>

<div>
  <%= link_to "Show this user", @user %> |
  <%= link_to "Back to users", users_path %>
</div>

app/views/users/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Users</h1>

<div id="users">
  <% @users.each do |user| %>
    <%= render user %>
    <p>
      <%= link_to "Show this user", user %>
    </p>
  <% end %>
</div>

<%= link_to "New user", new_user_path %>

app/views/users/new.html.erb
<h1>New user</h1>

<%= render "form", user: @user %>

<br>

<div>
  <%= link_to "Back to users", users_path %>
</div>

app/views/users/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @user %>

<div>
  <%= link_to "Edit this user", edit_user_path(@user) %> |
  <%= link_to "Back to users", users_path %>

  <%= button_to "Destroy this user", @user, method: :delete %>
</div>

app/views/welcome/index.html.erb
<div class="welcome">
  <h1 class="welcome-head">Budgetify</h1>
  <div class="welcome-div">
    <button class="welcome-button">
      <%= link_to "Sign up", new_user_registration_path, class: "welcome-link" %>
    </button>

    <button class="welcome-button">
      <%= link_to "Log in", new_user_session_path, class: "welcome-link" %>
    </button>
  </div>
  <p class="welcome-p">Budgetify is a user-friendly mobile app designed to streamline and simplify 
    the process of managing personal and business expenses. With its intuitive interface and 
    powerful features, Budgetify empowers users to take control of their finances, make informed financial decisions,
    and achieve their budgeting goals.</p>
</div>